/* Generated by Yosys 0.66 (git sha1 7f8fdfd8d7bc08c749a2a969388d3425d4f369d5, x86_64-w64-mingw32-g++ 16.1.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

module parity_generator(data, parity);
  input [7:0] data;
  wire [7:0] data;
  output parity;
  wire parity;
  wire [3:0] _0_;
  wire [1:0] _1_;
  \$_XOR_  _2_ (
    .A(data[0]),
    .B(data[1]),
    .Y(_0_[0])
  );
  \$_XOR_  _3_ (
    .A(data[2]),
    .B(data[3]),
    .Y(_0_[1])
  );
  \$_XOR_  _4_ (
    .A(data[4]),
    .B(data[5]),
    .Y(_0_[2])
  );
  \$_XOR_  _5_ (
    .A(data[6]),
    .B(data[7]),
    .Y(_0_[3])
  );
  \$_XOR_  _6_ (
    .A(_0_[0]),
    .B(_0_[1]),
    .Y(_1_[0])
  );
  \$_XOR_  _7_ (
    .A(_0_[2]),
    .B(_0_[3]),
    .Y(_1_[1])
  );
  \$_XOR_  _8_ (
    .A(_1_[0]),
    .B(_1_[1]),
    .Y(parity)
  );
endmodule
